CREATE TABLE IF NOT EXISTS `import_vehicles`(
    `id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `model` INT(3) NOT NULL UNIQUE,
    `price` INT(11) NOT NULL,
    `quantity` INT(11) NOT NULL,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB CHARSET="utf8" COLLATE="utf8_general_ci";