#define COLOR_WHITE             0xFFFFFFFF
#define COLOR_WHITE_EMBED       "FFFFFF"

#define COLOR_BLUE              0x00BBFFFF
#define COLOR_BLUE_EMBED        "00BBFF"

#define COLOR_RED               0xCD4F39FF
#define COLOR_RED_EMBED         "CD4F39"

#define COLOR_DARK              0x696969FF
#define COLOR_DARK_EMBED        "696969"

#define COLOR_GOLD              0xB8860BFF
#define COLOR_GOLD_EMBED        "B8860B"

#define COLOR_YELLOW            0xFFFF00FF
#define COLOR_YELLOW_EMBED      "FFFF00"

#define COLOR_ORANGE            0xFF8C00FF
#define COLOR_ORANGE_EMBED      "FF8C00"